version: '3.8'

services:

  mqtt_broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker
    ports:
      - "1883:1883"
    volumes: 
      - mosquitto_log:/mosquitto/log
      - mosquitto_data:/mosquitto/data
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - mqtt_network

  mqtt_publisher:
    build:
      context: ./Publisher_only
      dockerfile: Dockerfile.pub 
    container_name: mqtt_publisher
    depends_on:
      - mqtt_broker
    environment:
      - MQTT_BROKER_HOST=mqtt_broker
      - MQTT_BROKER_PORT=1883
    networks:
      - mqtt_network

  mqtt_subscriber:
    build:
      context: ./Listener_only
      dockerfile: Dockerfile.list
    container_name: mqtt_subscriber
    depends_on:
      - mqtt_broker
    environment:
      - MQTT_BROKER_HOST=mqtt_broker
      - MQTT_BROKER_PORT=1883
    networks:
      - mqtt_network

networks:
  mqtt_network:

volumes:
  mosquitto_log:
  mosquitto_data:
