# syntax=docker/dockerfile:1
FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-pip

RUN pip install paho-mqtt

WORKDIR /jolly

COPY . .

ENTRYPOINT [ "python3", "jolly.py" ]
